image: docker:20.10.16

stages:
  - push-ecr

.push-image: &push-image
  stage: push-ecr
  script:
    - docker image ls
    - podman build --force-rm -f Dockerfile -t pricing-app:${version}


push-dev:
  extends: .push-image

